title: "Benito Itele Wuver - Data Analyst Portfolio"
description: "Showcasing professional experience, skills, and projects."
theme: jekyll-theme-cayman
baseurl: "/data-analyst-portfolio"
url: "https://cliffinn.github.io"
github_username: cliffinn
email: benitoitelewuver@aol.com
show_downloads: true
